// flow-typed signature: 047d310dcaacc86c998c080688a45587
// flow-typed version: <<STUB>>/reduxsauce_v^0.5.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reduxsauce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reduxsauce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reduxsauce/dist/reduxsauce' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reduxsauce/dist/reduxsauce.js' {
  declare module.exports: $Exports<'reduxsauce/dist/reduxsauce'>;
}
